// AUTO-GENERATED by scripts/daily-devotional/devotional_pages.py - do not edit by hand.
export type Devo = { slug: string; date: string; dateDisplay: string; day: number | null; headline: string; verseRef: string | null; card: string | null }
export const devotionals: Devo[] = [
  {
    "slug": "how-do-i-stop-losing-my-mind-while-i-wait",
    "date": "2026-08-09",
    "dateDisplay": "9 August 2026",
    "day": 221,
    "headline": "How do I stop losing my mind while I wait?",
    "verseRef": "Psalm 46:10",
    "card": "/devotional-cards/how-do-i-stop-losing-my-mind-while-i-wait.jpg"
  },
  {
    "slug": "how-long-does-god-expect-me-to-keep-waiting",
    "date": "2026-08-08",
    "dateDisplay": "8 August 2026",
    "day": 220,
    "headline": "How long does God expect me to keep waiting?",
    "verseRef": "Psalm 27:14",
    "card": "/devotional-cards/how-long-does-god-expect-me-to-keep-waiting.jpg"
  },
  {
    "slug": "does-god-even-notice-how-tired-of-waiting-i-am",
    "date": "2026-08-07",
    "dateDisplay": "7 August 2026",
    "day": 219,
    "headline": "Does God even notice how tired of waiting I am?",
    "verseRef": "Psalm 13:1-2",
    "card": "/devotional-cards/does-god-even-notice-how-tired-of-waiting-i-am.jpg"
  },
  {
    "slug": "why-does-it-feel-like-god-has-forgotten-about-me",
    "date": "2026-08-06",
    "dateDisplay": "6 August 2026",
    "day": 218,
    "headline": "Why does it feel like God has forgotten about me?",
    "verseRef": "Isaiah 49:15-16",
    "card": "/devotional-cards/why-does-it-feel-like-god-has-forgotten-about-me.jpg"
  },
  {
    "slug": "will-god-still-provide-when-the-whole-year-has-been-hard",
    "date": "2026-08-05",
    "dateDisplay": "5 August 2026",
    "day": 217,
    "headline": "Will God still provide when the whole year has been hard?",
    "verseRef": "Psalm 37:25",
    "card": "/devotional-cards/will-god-still-provide-when-the-whole-year-has-been-hard.jpg"
  },
  {
    "slug": "will-this-money-stress-ever-actually-make-me-stronger",
    "date": "2026-08-04",
    "dateDisplay": "4 August 2026",
    "day": 216,
    "headline": "Will this money stress ever actually make me stronger?",
    "verseRef": "Romans 5:4",
    "card": "/devotional-cards/will-this-money-stress-ever-actually-make-me-stronger.jpg"
  },
  {
    "slug": "is-holding-back-money-the-same-as-not-trusting-god",
    "date": "2026-08-03",
    "dateDisplay": "3 August 2026",
    "day": 215,
    "headline": "Is holding back money the same as not trusting God?",
    "verseRef": "Proverbs 11:24",
    "card": "/devotional-cards/is-holding-back-money-the-same-as-not-trusting-god.jpg"
  },
  {
    "slug": "does-god-actually-have-practical-advice-for-my-money-problems",
    "date": "2026-08-02",
    "dateDisplay": "2 August 2026",
    "day": 214,
    "headline": "Does God actually have practical advice for my money problems?",
    "verseRef": "Proverbs 21:5",
    "card": "/devotional-cards/does-god-actually-have-practical-advice-for-my-money-problems.jpg"
  },
  {
    "slug": "is-god-actually-aware-of-what-i-cannot-afford-right-now",
    "date": "2026-08-01",
    "dateDisplay": "1 August 2026",
    "day": 213,
    "headline": "Is God actually aware of what I cannot afford right now?",
    "verseRef": "Matthew 6:31-32",
    "card": "/devotional-cards/is-god-actually-aware-of-what-i-cannot-afford-right-now.jpg"
  },
  {
    "slug": "why-do-i-feel-ashamed-that-i-am-struggling-financially",
    "date": "2026-07-31",
    "dateDisplay": "31 July 2026",
    "day": 212,
    "headline": "Why do I feel ashamed that I am struggling financially?",
    "verseRef": "Psalm 34:10",
    "card": "/devotional-cards/why-do-i-feel-ashamed-that-i-am-struggling-financially.jpg"
  },
  {
    "slug": "why-does-money-stress-feel-like-it-never-fully-goes-away",
    "date": "2026-07-30",
    "dateDisplay": "30 July 2026",
    "day": 211,
    "headline": "Why does money stress feel like it never fully goes away?",
    "verseRef": "Philippians 4:19",
    "card": "/devotional-cards/why-does-money-stress-feel-like-it-never-fully-goes-away.jpg"
  },
  {
    "slug": "will-the-small-things-i-did-for-my-family-actually-matter-in-the-end",
    "date": "2026-07-29",
    "dateDisplay": "29 July 2026",
    "day": 210,
    "headline": "Will the small things I did for my family actually matter in the end?",
    "verseRef": "Psalm 90:17",
    "card": "/devotional-cards/will-the-small-things-i-did-for-my-family-actually-matter-in-the-end.jpg"
  },
  {
    "slug": "is-god-actually-doing-something-with-the-mess-in-my-home",
    "date": "2026-07-28",
    "dateDisplay": "28 July 2026",
    "day": 209,
    "headline": "Is God actually doing something with the mess in my home?",
    "verseRef": "1 Corinthians 3:9",
    "card": "/devotional-cards/is-god-actually-doing-something-with-the-mess-in-my-home.jpg"
  },
  {
    "slug": "am-i-actually-present-at-home-or-just-physically-there",
    "date": "2026-07-27",
    "dateDisplay": "27 July 2026",
    "day": 208,
    "headline": "Am I actually present at home, or just physically there?",
    "verseRef": "Deuteronomy 6:6-7",
    "card": "/devotional-cards/am-i-actually-present-at-home-or-just-physically-there.jpg"
  },
  {
    "slug": "how-do-i-stop-saying-things-i-regret-to-the-people-i-love",
    "date": "2026-07-26",
    "dateDisplay": "26 July 2026",
    "day": 207,
    "headline": "How do I stop saying things I regret to the people I love?",
    "verseRef": "Proverbs 21:23",
    "card": "/devotional-cards/how-do-i-stop-saying-things-i-regret-to-the-people-i-love.jpg"
  },
  {
    "slug": "is-it-possible-to-actually-love-my-family-well-when-im-this-depleted",
    "date": "2026-07-25",
    "dateDisplay": "25 July 2026",
    "day": 206,
    "headline": "Is it possible to actually love my family well when I'm this depleted?",
    "verseRef": "Isaiah 40:31",
    "card": "/devotional-cards/is-it-possible-to-actually-love-my-family-well-when-im-this-depleted.jpg"
  },
  {
    "slug": "why-do-i-snap-at-the-people-i-love-most",
    "date": "2026-07-24",
    "dateDisplay": "24 July 2026",
    "day": 205,
    "headline": "Why do I snap at the people I love most?",
    "verseRef": "Proverbs 15:1",
    "card": "/devotional-cards/why-do-i-snap-at-the-people-i-love-most.jpg"
  },
  {
    "slug": "how-do-i-stay-calm-when-home-feels-chaotic",
    "date": "2026-07-23",
    "dateDisplay": "23 July 2026",
    "day": 204,
    "headline": "How do I stay calm when home feels chaotic?",
    "verseRef": "Psalm 46:1",
    "card": "/devotional-cards/how-do-i-stay-calm-when-home-feels-chaotic.jpg"
  },
  {
    "slug": "when-i-look-back-at-my-life-has-god-actually-been-faithful",
    "date": "2026-07-22",
    "dateDisplay": "22 July 2026",
    "day": 203,
    "headline": "When I look back at my life, has God actually been faithful?",
    "verseRef": "Psalm 23:6",
    "card": "/devotional-cards/when-i-look-back-at-my-life-has-god-actually-been-faithful.jpg"
  },
  {
    "slug": "what-is-god-actually-doing-while-i-am-this-exhausted",
    "date": "2026-07-21",
    "dateDisplay": "21 July 2026",
    "day": 202,
    "headline": "What is God actually doing while I am this exhausted?",
    "verseRef": "Romans 5:3-4",
    "card": "/devotional-cards/what-is-god-actually-doing-while-i-am-this-exhausted.jpg"
  },
  {
    "slug": "am-i-resting-in-god-or-just-avoiding-the-hard-thing",
    "date": "2026-07-20",
    "dateDisplay": "20 July 2026",
    "day": 201,
    "headline": "Am I resting in God or just avoiding the hard thing?",
    "verseRef": "Psalm 46:10",
    "card": "/devotional-cards/am-i-resting-in-god-or-just-avoiding-the-hard-thing.jpg"
  },
  {
    "slug": "how-do-i-know-when-to-push-through-and-when-to-stop",
    "date": "2026-07-19",
    "dateDisplay": "19 July 2026",
    "day": 200,
    "headline": "How do I know when to push through and when to stop?",
    "verseRef": "Proverbs 4:26",
    "card": "/devotional-cards/how-do-i-know-when-to-push-through-and-when-to-stop.jpg"
  },
  {
    "slug": "what-if-i-cant-stop-feeling-overwhelmed",
    "date": "2026-07-18",
    "dateDisplay": "18 July 2026",
    "day": 199,
    "headline": "What if I can't stop feeling overwhelmed?",
    "verseRef": "Isaiah 41:10",
    "card": "/devotional-cards/what-if-i-cant-stop-feeling-overwhelmed.jpg"
  },
  {
    "slug": "why-do-i-feel-so-tired-inside-all-the-time",
    "date": "2026-07-17",
    "dateDisplay": "17 July 2026",
    "day": 198,
    "headline": "Why do I feel so tired inside all the time?",
    "verseRef": "Isaiah 40:29",
    "card": "/devotional-cards/why-do-i-feel-so-tired-inside-all-the-time.jpg"
  },
  {
    "slug": "how-do-i-find-rest-when-im-overwhelmed",
    "date": "2026-07-16",
    "dateDisplay": "16 July 2026",
    "day": 197,
    "headline": "How do I find rest when I'm overwhelmed?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/how-do-i-find-rest-when-im-overwhelmed.jpg"
  },
  {
    "slug": "how-does-gods-faithfulness-look-over-my-whole-life",
    "date": "2026-07-15",
    "dateDisplay": "15 July 2026",
    "day": 196,
    "headline": "How does God's faithfulness look over my whole life?",
    "verseRef": "Lamentations 3:22-23",
    "card": "/devotional-cards/how-does-gods-faithfulness-look-over-my-whole-life.jpg"
  },
  {
    "slug": "how-can-i-see-what-god-is-forming-in-me",
    "date": "2026-07-14",
    "dateDisplay": "14 July 2026",
    "day": 195,
    "headline": "How can I see what God is forming in me?",
    "verseRef": "Philippians 1:6",
    "card": "/devotional-cards/how-can-i-see-what-god-is-forming-in-me.jpg"
  },
  {
    "slug": "how-do-i-keep-joy-when-i-keep-comparing-myself",
    "date": "2026-07-13",
    "dateDisplay": "13 July 2026",
    "day": 194,
    "headline": "How do I keep joy when I keep comparing myself?",
    "verseRef": "2 Corinthians 10:12",
    "card": "/devotional-cards/how-do-i-keep-joy-when-i-keep-comparing-myself.jpg"
  },
  {
    "slug": "how-do-i-stop-my-mind-from-ruining-a-good-day",
    "date": "2026-07-12",
    "dateDisplay": "12 July 2026",
    "day": 193,
    "headline": "How do I stop my mind from ruining a good day?",
    "verseRef": "Philippians 4:8",
    "card": "/devotional-cards/how-do-i-stop-my-mind-from-ruining-a-good-day.jpg"
  },
  {
    "slug": "can-you-really-be-joyful-when-nothing-has-changed-yet",
    "date": "2026-07-11",
    "dateDisplay": "11 July 2026",
    "day": 192,
    "headline": "Can you really be joyful when nothing has changed yet?",
    "verseRef": "Habakkuk 3:17-18",
    "card": "/devotional-cards/can-you-really-be-joyful-when-nothing-has-changed-yet.jpg"
  },
  {
    "slug": "how-do-you-stay-grateful-when-life-just-feels-heavy",
    "date": "2026-07-10",
    "dateDisplay": "10 July 2026",
    "day": 191,
    "headline": "How do you stay grateful when life just feels heavy?",
    "verseRef": "Psalm 34:18",
    "card": "/devotional-cards/how-do-you-stay-grateful-when-life-just-feels-heavy.jpg"
  },
  {
    "slug": "why-does-it-feel-like-i-have-nothing-to-be-thankful-for",
    "date": "2026-07-09",
    "dateDisplay": "9 July 2026",
    "day": 190,
    "headline": "Why does it feel like I have nothing to be thankful for?",
    "verseRef": "Psalm 103:2",
    "card": "/devotional-cards/why-does-it-feel-like-i-have-nothing-to-be-thankful-for.jpg"
  },
  {
    "slug": "does-god-actually-remember-everything-i-have-been-through",
    "date": "2026-07-08",
    "dateDisplay": "8 July 2026",
    "day": 189,
    "headline": "Does God actually remember everything I have been through?",
    "verseRef": "Psalm 77:11",
    "card": "/devotional-cards/does-god-actually-remember-everything-i-have-been-through.jpg"
  },
  {
    "slug": "is-god-doing-something-in-me-even-when-prayer-feels-pointless",
    "date": "2026-07-07",
    "dateDisplay": "7 July 2026",
    "day": 188,
    "headline": "Is God doing something in me even when prayer feels pointless?",
    "verseRef": "James 1:3-4",
    "card": "/devotional-cards/is-god-doing-something-in-me-even-when-prayer-feels-pointless.jpg"
  },
  {
    "slug": "what-if-god-is-waiting-for-me-to-be-honest-with-him",
    "date": "2026-07-06",
    "dateDisplay": "6 July 2026",
    "day": 187,
    "headline": "What if God is waiting for me to be honest with Him?",
    "verseRef": "Psalm 62:8",
    "card": "/devotional-cards/what-if-god-is-waiting-for-me-to-be-honest-with-him.jpg"
  },
  {
    "slug": "you-pray-the-same-thing-every-day-and-wonder-why",
    "date": "2026-07-05",
    "dateDisplay": "5 July 2026",
    "day": 186,
    "headline": "You pray the same thing every day and wonder why",
    "verseRef": "Romans 8:26",
    "card": "/devotional-cards/you-pray-the-same-thing-every-day-and-wonder-why.jpg"
  },
  {
    "slug": "is-it-too-late-to-make-up-for-missing-time-with-my-child",
    "date": "2026-07-04",
    "dateDisplay": "4 July 2026",
    "day": 185,
    "headline": "Is it too late to make up for missing time with my child?",
    "verseRef": "Matthew 19:14",
    "card": "/devotional-cards/is-it-too-late-to-make-up-for-missing-time-with-my-child.jpg"
  },
  {
    "slug": "why-does-spending-time-with-my-family-still-feel-empty",
    "date": "2026-07-03",
    "dateDisplay": "3 July 2026",
    "day": 184,
    "headline": "Why does spending time with my family still feel empty?",
    "verseRef": "Matthew 22:37-39",
    "card": "/devotional-cards/why-does-spending-time-with-my-family-still-feel-empty.jpg"
  },
  {
    "slug": "why-am-i-always-busy-but-still-feel-like-nothing-matters",
    "date": "2026-07-02",
    "dateDisplay": "2 July 2026",
    "day": 183,
    "headline": "Why am I always busy but still feel like nothing matters?",
    "verseRef": "Psalm 46:10",
    "card": "/devotional-cards/why-am-i-always-busy-but-still-feel-like-nothing-matters.jpg"
  },
  {
    "slug": "why-do-i-feel-empty-even-when-i-get-everything-done",
    "date": "2026-07-01",
    "dateDisplay": "1 July 2026",
    "day": 182,
    "headline": "Why do I feel empty even when I get everything done?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/why-do-i-feel-empty-even-when-i-get-everything-done.jpg"
  },
  {
    "slug": "is-it-okay-to-cry-even-when-you-believe-in-god",
    "date": "2026-06-30",
    "dateDisplay": "30 June 2026",
    "day": 181,
    "headline": "Is it okay to cry even when you believe in God?",
    "verseRef": "John 11:35",
    "card": "/devotional-cards/is-it-okay-to-cry-even-when-you-believe-in-god.jpg"
  },
  {
    "slug": "is-it-okay-to-have-doubts-about-your-faith",
    "date": "2026-06-29",
    "dateDisplay": "29 June 2026",
    "day": 180,
    "headline": "Is it okay to have doubts about your faith?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/is-it-okay-to-have-doubts-about-your-faith.jpg"
  },
  {
    "slug": "is-it-weak-to-ask-for-help-when-you-are-struggling",
    "date": "2026-06-28",
    "dateDisplay": "28 June 2026",
    "day": 179,
    "headline": "Is it weak to ask for help when you are struggling?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/is-it-weak-to-ask-for-help-when-you-are-struggling.jpg"
  },
  {
    "slug": "how-do-i-tell-someone-i-care-about-them-without-being-scared",
    "date": "2026-06-27",
    "dateDisplay": "27 June 2026",
    "day": 178,
    "headline": "How do I tell someone I care about them without being scared?",
    "verseRef": "Matthew 7:12",
    "card": "/devotional-cards/how-do-i-tell-someone-i-care-about-them-without-being-scared.jpg"
  },
  {
    "slug": "is-it-okay-to-finally-leave-something-i-stayed-in-too-long",
    "date": "2026-06-26",
    "dateDisplay": "26 June 2026",
    "day": 177,
    "headline": "Is it okay to finally leave something I stayed in too long?",
    "verseRef": "John 8:32",
    "card": "/devotional-cards/is-it-okay-to-finally-leave-something-i-stayed-in-too-long.jpg"
  },
  {
    "slug": "is-it-okay-to-stop-pretending-everything-is-fine",
    "date": "2026-06-25",
    "dateDisplay": "25 June 2026",
    "day": 176,
    "headline": "Is it okay to stop pretending everything is fine?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/is-it-okay-to-stop-pretending-everything-is-fine.jpg"
  },
  {
    "slug": "is-it-okay-to-cry-and-grieve-when-you-are-a-christian",
    "date": "2026-06-24",
    "dateDisplay": "24 June 2026",
    "day": 175,
    "headline": "Is it okay to cry and grieve when you are a Christian?",
    "verseRef": "John 11:35",
    "card": "/devotional-cards/is-it-okay-to-cry-and-grieve-when-you-are-a-christian.jpg"
  },
  {
    "slug": "how-do-i-stop-performing-and-just-be-myself",
    "date": "2026-06-23",
    "dateDisplay": "23 June 2026",
    "day": 174,
    "headline": "How do I stop performing and just be myself?",
    "verseRef": "Genesis 16:13",
    "card": "/devotional-cards/how-do-i-stop-performing-and-just-be-myself.jpg"
  },
  {
    "slug": "why-am-i-so-exhausted-from-trying-to-keep-everyone-happy",
    "date": "2026-06-22",
    "dateDisplay": "22 June 2026",
    "day": 173,
    "headline": "Why am I so exhausted from trying to keep everyone happy?",
    "verseRef": "Galatians 1:10",
    "card": "/devotional-cards/why-am-i-so-exhausted-from-trying-to-keep-everyone-happy.jpg"
  },
  {
    "slug": "is-it-okay-to-admit-i-am-struggling-and-need-help",
    "date": "2026-06-21",
    "dateDisplay": "21 June 2026",
    "day": 172,
    "headline": "Is it okay to admit I am struggling and need help?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/is-it-okay-to-admit-i-am-struggling-and-need-help.jpg"
  },
  {
    "slug": "why-do-i-always-stay-quiet-and-hide-who-i-really-am",
    "date": "2026-06-20",
    "dateDisplay": "20 June 2026",
    "day": 171,
    "headline": "Why do I always stay quiet and hide who I really am?",
    "verseRef": "Matthew 5:14",
    "card": "/devotional-cards/why-do-i-always-stay-quiet-and-hide-who-i-really-am.jpg"
  },
  {
    "slug": "why-am-i-always-pretending-to-be-okay-around-people",
    "date": "2026-06-19",
    "dateDisplay": "19 June 2026",
    "day": 170,
    "headline": "Why am I always pretending to be okay around people?",
    "verseRef": "John 8:32",
    "card": "/devotional-cards/why-am-i-always-pretending-to-be-okay-around-people.jpg"
  },
  {
    "slug": "why-do-i-feel-so-alone-even-when-everyone-depends-on-me",
    "date": "2026-06-18",
    "dateDisplay": "18 June 2026",
    "day": 169,
    "headline": "Why do I feel so alone even when everyone depends on me?",
    "verseRef": "2 Corinthians 5:17",
    "card": "/devotional-cards/why-do-i-feel-so-alone-even-when-everyone-depends-on-me.jpg"
  },
  {
    "slug": "why-do-i-act-like-a-different-person-around-different-people",
    "date": "2026-06-17",
    "dateDisplay": "17 June 2026",
    "day": 168,
    "headline": "Why do I act like a different person around different people?",
    "verseRef": "Matthew 5:48",
    "card": "/devotional-cards/why-do-i-act-like-a-different-person-around-different-people.jpg"
  },
  {
    "slug": "how-do-i-actually-rest-when-my-mind-wont-stop",
    "date": "2026-06-16",
    "dateDisplay": "16 June 2026",
    "day": 167,
    "headline": "How do I actually rest when my mind won't stop?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/how-do-i-actually-rest-when-my-mind-wont-stop.jpg"
  },
  {
    "slug": "how-do-i-find-my-purpose-again-when-i-feel-completely-burnt-out",
    "date": "2026-06-15",
    "dateDisplay": "15 June 2026",
    "day": 166,
    "headline": "How do I find my purpose again when I feel completely burnt out?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/how-do-i-find-my-purpose-again-when-i-feel-completely-burnt-out.jpg"
  },
  {
    "slug": "why-am-i-always-tired-no-matter-how-much-i-rest",
    "date": "2026-06-14",
    "dateDisplay": "14 June 2026",
    "day": 165,
    "headline": "Why am I always tired no matter how much I rest?",
    "verseRef": "Matthew 26:41",
    "card": "/devotional-cards/why-am-i-always-tired-no-matter-how-much-i-rest.jpg"
  },
  {
    "slug": "why-do-i-feel-exhausted-from-always-trying-to-hold-everything-together",
    "date": "2026-06-13",
    "dateDisplay": "13 June 2026",
    "day": 164,
    "headline": "Why do I feel exhausted from always trying to hold everything together?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/why-do-i-feel-exhausted-from-always-trying-to-hold-everything-together.jpg"
  },
  {
    "slug": "how-do-i-know-if-im-running-toward-the-wrong-goal-in-life",
    "date": "2026-06-12",
    "dateDisplay": "12 June 2026",
    "day": 163,
    "headline": "How do I know if I'm running toward the wrong goal in life?",
    "verseRef": "Romans 8:2",
    "card": "/devotional-cards/how-do-i-know-if-im-running-toward-the-wrong-goal-in-life.jpg"
  },
  {
    "slug": "why-do-i-feel-guilty-saying-no-to-people-who-need-me",
    "date": "2026-06-11",
    "dateDisplay": "11 June 2026",
    "day": 162,
    "headline": "Why do I feel guilty saying no to people who need me?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/why-do-i-feel-guilty-saying-no-to-people-who-need-me.jpg"
  },
  {
    "slug": "why-am-i-exhausted-even-after-sleeping-enough",
    "date": "2026-06-10",
    "dateDisplay": "10 June 2026",
    "day": 161,
    "headline": "Why am I exhausted even after sleeping enough?",
    "verseRef": "Romans 12:2",
    "card": "/devotional-cards/why-am-i-exhausted-even-after-sleeping-enough.jpg"
  },
  {
    "slug": "why-have-i-lost-my-drive-now-that-im-more-successful",
    "date": "2026-06-09",
    "dateDisplay": "9 June 2026",
    "day": 160,
    "headline": "Why have I lost my drive now that I'm more successful?",
    "verseRef": "Revelation 3:17",
    "card": "/devotional-cards/why-have-i-lost-my-drive-now-that-im-more-successful.jpg"
  },
  {
    "slug": "how-do-i-stop-being-too-scared-to-start-something-new",
    "date": "2026-06-08",
    "dateDisplay": "8 June 2026",
    "day": 159,
    "headline": "How do I stop being too scared to start something new?",
    "verseRef": "2 Timothy 1:7",
    "card": "/devotional-cards/how-do-i-stop-being-too-scared-to-start-something-new.jpg"
  },
  {
    "slug": "why-do-i-keep-talking-about-my-goals-but-never-actually-start",
    "date": "2026-06-07",
    "dateDisplay": "7 June 2026",
    "day": 158,
    "headline": "Why do I keep talking about my goals but never actually start?",
    "verseRef": "James 2:17",
    "card": "/devotional-cards/why-do-i-keep-talking-about-my-goals-but-never-actually-start.jpg"
  },
  {
    "slug": "what-if-i-start-something-but-cant-keep-it-going",
    "date": "2026-06-06",
    "dateDisplay": "6 June 2026",
    "day": 157,
    "headline": "What if I start something but can't keep it going?",
    "verseRef": "2 Timothy 1:7",
    "card": "/devotional-cards/what-if-i-start-something-but-cant-keep-it-going.jpg"
  },
  {
    "slug": "how-do-i-stop-waiting-for-a-sign-and-just-start",
    "date": "2026-06-05",
    "dateDisplay": "5 June 2026",
    "day": 156,
    "headline": "How do I stop waiting for a sign and just start?",
    "verseRef": "James 4:17",
    "card": "/devotional-cards/how-do-i-stop-waiting-for-a-sign-and-just-start.jpg"
  },
  {
    "slug": "how-do-i-stop-over-researching-and-actually-start-doing-the-thing",
    "date": "2026-06-04",
    "dateDisplay": "4 June 2026",
    "day": 155,
    "headline": "How do I stop over-researching and actually start doing the thing?",
    "verseRef": "James 2:26",
    "card": "/devotional-cards/how-do-i-stop-over-researching-and-actually-start-doing-the-thing.jpg"
  },
  {
    "slug": "how-do-i-stop-waiting-until-i-feel-ready-to-start",
    "date": "2026-06-03",
    "dateDisplay": "3 June 2026",
    "day": 154,
    "headline": "How do I stop waiting until I feel ready to start?",
    "verseRef": "2 Corinthians 5:7",
    "card": "/devotional-cards/how-do-i-stop-waiting-until-i-feel-ready-to-start.jpg"
  },
  {
    "slug": "why-do-i-feel-so-lonely-even-though-i-have-lots-of-friends",
    "date": "2026-06-02",
    "dateDisplay": "2 June 2026",
    "day": 153,
    "headline": "Why do I feel so lonely even though I have lots of friends?",
    "verseRef": "Proverbs 18:24",
    "card": "/devotional-cards/why-do-i-feel-so-lonely-even-though-i-have-lots-of-friends.jpg"
  },
  {
    "slug": "why-do-i-feel-like-every-act-of-kindness-has-hidden-strings-attached",
    "date": "2026-06-01",
    "dateDisplay": "1 June 2026",
    "day": 152,
    "headline": "Why do I feel like every act of kindness has hidden strings attached?",
    "verseRef": "1 John 4:10",
    "card": "/devotional-cards/why-do-i-feel-like-every-act-of-kindness-has-hidden-strings-attached.jpg"
  },
  {
    "slug": "is-staying-in-a-painful-relationship-really-love-or-just-fear",
    "date": "2026-05-31",
    "dateDisplay": "31 May 2026",
    "day": 151,
    "headline": "Is staying in a painful relationship really love or just fear?",
    "verseRef": "Matthew 10:14",
    "card": "/devotional-cards/is-staying-in-a-painful-relationship-really-love-or-just-fear.jpg"
  },
  {
    "slug": "how-do-i-know-if-someone-loves-me-or-just-needs-me",
    "date": "2026-05-30",
    "dateDisplay": "30 May 2026",
    "day": 150,
    "headline": "How do I know if someone loves me or just needs me?",
    "verseRef": "John 15:13",
    "card": "/devotional-cards/how-do-i-know-if-someone-loves-me-or-just-needs-me.jpg"
  },
  {
    "slug": "what-happens-when-you-stop-pretending-to-be-someone-youre-not",
    "date": "2026-05-29",
    "dateDisplay": "29 May 2026",
    "day": 149,
    "headline": "What happens when you stop pretending to be someone you're not?",
    "verseRef": "Matthew 16:26",
    "card": "/devotional-cards/what-happens-when-you-stop-pretending-to-be-someone-youre-not.jpg"
  },
  {
    "slug": "why-do-i-feel-exhausted-from-always-being-there-for-everyone",
    "date": "2026-05-28",
    "dateDisplay": "28 May 2026",
    "day": 148,
    "headline": "Why do I feel exhausted from always being there for everyone?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/why-do-i-feel-exhausted-from-always-being-there-for-everyone.jpg"
  },
  {
    "slug": "why-do-i-always-give-more-than-i-receive-in-relationships",
    "date": "2026-05-27",
    "dateDisplay": "27 May 2026",
    "day": 147,
    "headline": "Why do I always give more than I receive in relationships?",
    "verseRef": "Matthew 22:39",
    "card": "/devotional-cards/why-do-i-always-give-more-than-i-receive-in-relationships.jpg"
  },
  {
    "slug": "how-do-i-stop-waiting-and-start-taking-action-finally",
    "date": "2026-05-26",
    "dateDisplay": "26 May 2026",
    "day": 146,
    "headline": "How do I stop waiting and start taking action finally?",
    "verseRef": "Matthew 6:34",
    "card": "/devotional-cards/how-do-i-stop-waiting-and-start-taking-action-finally.jpg"
  },
  {
    "slug": "why-do-i-stay-busy-but-never-actually-change-anything",
    "date": "2026-05-25",
    "dateDisplay": "25 May 2026",
    "day": 145,
    "headline": "Why do I stay busy but never actually change anything?",
    "verseRef": "Hebrews 12:1",
    "card": "/devotional-cards/why-do-i-stay-busy-but-never-actually-change-anything.jpg"
  },
  {
    "slug": "why-do-i-keep-making-excuses-to-avoid-facing-the-truth",
    "date": "2026-05-24",
    "dateDisplay": "24 May 2026",
    "day": 144,
    "headline": "Why do I keep making excuses to avoid facing the truth?",
    "verseRef": "John 8:32",
    "card": "/devotional-cards/why-do-i-keep-making-excuses-to-avoid-facing-the-truth.jpg"
  },
  {
    "slug": "why-do-i-keep-scrolling-my-phone-instead-of-sleeping",
    "date": "2026-05-23",
    "dateDisplay": "23 May 2026",
    "day": 143,
    "headline": "Why do I keep scrolling my phone instead of sleeping?",
    "verseRef": "Psalm 55:22",
    "card": "/devotional-cards/why-do-i-keep-scrolling-my-phone-instead-of-sleeping.jpg"
  },
  {
    "slug": "why-do-i-keep-picking-fights-over-stupid-little-things",
    "date": "2026-05-22",
    "dateDisplay": "22 May 2026",
    "day": 142,
    "headline": "Why do I keep picking fights over stupid little things?",
    "verseRef": "Psalm 46:10",
    "card": "/devotional-cards/why-do-i-keep-picking-fights-over-stupid-little-things.jpg"
  },
  {
    "slug": "why-do-i-keep-avoiding-a-difficult-conversation-i-need-to-have",
    "date": "2026-05-21",
    "dateDisplay": "21 May 2026",
    "day": 141,
    "headline": "Why do I keep avoiding a difficult conversation I need to have?",
    "verseRef": "Luke 12:2",
    "card": "/devotional-cards/why-do-i-keep-avoiding-a-difficult-conversation-i-need-to-have.jpg"
  },
  {
    "slug": "why-am-i-so-afraid-of-being-alone-with-my-thoughts",
    "date": "2026-05-20",
    "dateDisplay": "20 May 2026",
    "day": 140,
    "headline": "Why am I so afraid of being alone with my thoughts?",
    "verseRef": "Psalm 46:10",
    "card": "/devotional-cards/why-am-i-so-afraid-of-being-alone-with-my-thoughts.jpg"
  },
  {
    "slug": "do-my-small-daily-actions-actually-matter-in-the-long-run",
    "date": "2026-05-19",
    "dateDisplay": "19 May 2026",
    "day": 139,
    "headline": "Do my small daily actions actually matter in the long run?",
    "verseRef": "Jeremiah 29:11",
    "card": "/devotional-cards/do-my-small-daily-actions-actually-matter-in-the-long-run.jpg"
  },
  {
    "slug": "how-do-i-stop-trying-to-control-everything-in-my-life",
    "date": "2026-05-18",
    "dateDisplay": "18 May 2026",
    "day": 138,
    "headline": "How do I stop trying to control everything in my life?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/how-do-i-stop-trying-to-control-everything-in-my-life.jpg"
  },
  {
    "slug": "does-my-job-or-role-actually-define-who-i-am",
    "date": "2026-05-17",
    "dateDisplay": "17 May 2026",
    "day": 137,
    "headline": "Does my job or role actually define who I am?",
    "verseRef": "2 Corinthians 5:17",
    "card": "/devotional-cards/does-my-job-or-role-actually-define-who-i-am.jpg"
  },
  {
    "slug": "how-do-i-stop-wasting-time-and-actually-live-with-purpose",
    "date": "2026-05-16",
    "dateDisplay": "16 May 2026",
    "day": 136,
    "headline": "How do I stop wasting time and actually live with purpose?",
    "verseRef": "Ephesians 5:16",
    "card": "/devotional-cards/how-do-i-stop-wasting-time-and-actually-live-with-purpose.jpg"
  },
  {
    "slug": "how-do-i-cope-when-life-feels-too-heavy-to-bear",
    "date": "2026-05-15",
    "dateDisplay": "15 May 2026",
    "day": 135,
    "headline": "How do I cope when life feels too heavy to bear?",
    "verseRef": "Matthew 11:28",
    "card": "/devotional-cards/how-do-i-cope-when-life-feels-too-heavy-to-bear.jpg"
  },
  {
    "slug": "when-god-seems-silent",
    "date": "2026-05-01",
    "dateDisplay": "1 May 2026",
    "day": null,
    "headline": "When God Seems Silent",
    "verseRef": "Isaiah 40:31",
    "card": null
  },
  {
    "slug": "one-question-before-sunday",
    "date": "2026-05-01",
    "dateDisplay": "1 May 2026",
    "day": null,
    "headline": "One Question Before Sunday",
    "verseRef": "Matthew 7:7",
    "card": null
  },
  {
    "slug": "what-sunday-is-not",
    "date": "2026-05-01",
    "dateDisplay": "1 May 2026",
    "day": null,
    "headline": "What Sunday Is Not",
    "verseRef": "Luke 5:31",
    "card": null
  },
  {
    "slug": "the-week-did-not-go-as-planned",
    "date": "2026-05-01",
    "dateDisplay": "1 May 2026",
    "day": null,
    "headline": "The Week Did Not Go As Planned",
    "verseRef": "Psalm 34:18",
    "card": null
  },
  {
    "slug": "prepare-your-heart-before-you-walk-in",
    "date": "2026-04-27",
    "dateDisplay": "27 April 2026",
    "day": null,
    "headline": "Prepare Your Heart Before You Walk In",
    "verseRef": "Matthew 11:28",
    "card": null
  }
]
