import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://www.fountaingrace.org'
  const now = new Date()

  return [
    // Core pages
    { url: base, lastModified: now, changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/plan-your-visit`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/community-impact`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/donate`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/about`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/what-to-expect`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/contact`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/pastors`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/volunteer`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/prayer`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/faq`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/what-we-believe`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    // Sermons
    { url: `${base}/sermons`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${base}/sermons/you-work-hard-but-nothing-changes-heres-what-youre-missing`, lastModified: new Date('2023-04-06'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-past-mistakes-dont-determine-your-future`, lastModified: new Date('2023-04-14'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/stuck-in-a-dead-relationship-or-job-heres-why-you-wont-leave`, lastModified: new Date('2024-01-28'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-shortcut-thats-ruining-your-life`, lastModified: new Date('2023-03-05'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-exhausted-from-making-life-harder-than-it-has-to-be`, lastModified: new Date('2022-08-14'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/everyones-rejected-you-heres-what-that-really-means-about-your-worth`, lastModified: new Date('2022-07-31'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/theyre-using-you-and-god-is-too`, lastModified: new Date('2022-08-07'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-exhausted-because-youre-trying-to-do-everything-alone`, lastModified: new Date('2022-07-24'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-feel-trapped-by-what-others-say-you-cant-do`, lastModified: new Date('2022-11-27'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-struggles-arent-wasting-your-life-theyre-building-you-for-something`, lastModified: new Date('2022-09-18'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-about-to-quit-right-before-everything-changes`, lastModified: new Date('2022-07-10'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-blocked-by-one-thing-and-dont-even-know-it`, lastModified: new Date('2022-12-11'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-success-depends-on-what-you-do-before-it-arrives`, lastModified: new Date('2024-06-16'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/stop-waiting-to-be-perfect-before-you-matter`, lastModified: new Date('2024-03-03'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-not-beyond-repair-no-matter-what-youve-done`, lastModified: new Date('2026-06-14'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/stop-wasting-energy-on-people-who-wont-listen`, lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-you-stop-hearing-the-voice-that-used-to-guide-every-decision`, lastModified: new Date('2026-05-10'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-the-easy-road-always-leads-to-the-wrong-place`, lastModified: new Date('2026-05-17'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-already-know-what-to-do-so-why-arent-you-doing-it`, lastModified: new Date('2026-03-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-pain-you-inherited-from-your-father-is-quietly-breaking-your-kids`, lastModified: new Date('2025-06-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-life-falls-apart-under-pressure-because-of-whats-actually-inside-you`, lastModified: new Date('2026-01-18'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/everyone-around-you-is-pretending-heres-why-youre-alone`, lastModified: new Date('2026-05-24'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-hidden-cost-of-staying-silent-at-work-home-and-in-life`, lastModified: new Date('2026-05-31'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/how-to-know-if-that-gut-feeling-is-real-guidance-or-just-your-own-fear`, lastModified: new Date('2024-10-27'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/six-invisible-gaps-that-wreck-your-life-and-how-to-close-them`, lastModified: new Date('2025-01-19'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/stop-waiting-for-permission-to-become-who-you-already-are`, lastModified: new Date('2024-10-04'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/stop-waiting-for-someone-else-to-tell-you-whats-coming`, lastModified: new Date('2024-11-10'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-life-knocks-you-down-does-integrity-actually-matter`, lastModified: new Date('2025-03-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-small-habits-that-quietly-destroy-your-life`, lastModified: new Date('2024-12-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-one-conversation-that-stops-relationship-arguments-before-they-start`, lastModified: new Date('2024-10-13'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/how-to-know-what-to-do-when-everything-feels-confusing`, lastModified: new Date('2024-11-03'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-cost-of-sitting-on-the-sidelines`, lastModified: new Date('2025-02-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-person-nobody-checks-on-how-youre-losing-friends-without-knowing-it`, lastModified: new Date('2024-12-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-mind-is-broken-by-lies-you-believed-heres-how-to-rebuild-it`, lastModified: new Date('2025-01-12'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-life-deliberately-gets-worse-before-it-works-out`, lastModified: new Date('2025-03-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-real-reason-youre-trapped-in-debt-and-how-to-break-free`, lastModified: new Date('2024-12-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-got-what-you-prayed-for-but-lost-it-anyway`, lastModified: new Date('2025-01-31'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-person-who-notices-when-you-disappear`, lastModified: new Date('2025-02-21'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-dreams-feel-dead-but-delays-arent-denials-heres-why`, lastModified: new Date('2025-03-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-your-preparation-matters-more-than-your-luck`, lastModified: new Date('2025-03-22'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-your-biggest-dreams-attract-the-strongest-opposition`, lastModified: new Date('2025-03-30'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/false-accusations-wont-stop-your-dreams-what-josephs-story-reveals`, lastModified: new Date('2025-04-06'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-your-kindness-might-be-hurting-people`, lastModified: new Date('2025-04-12'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-jesus-changed-everything-the-birth-that-brings-new-life`, lastModified: new Date('2025-06-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-youre-losing-battles-and-how-to-actually-win`, lastModified: new Date('2025-06-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/i-nearly-died-this-week-heres-what-changed-everything`, lastModified: new Date('2026-04-29'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-youre-busy-but-stuck-the-action-that-actually-works`, lastModified: new Date('2026-05-11'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/youre-still-in-the-story-when-god-seems-silent`, lastModified: new Date('2026-05-16'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-you-cant-believe-things-will-get-better-again`, lastModified: new Date('2026-04-26'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/tired-of-the-same-pain-coming-back-try-this`, lastModified: new Date('2025-12-14'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-life-feels-like-a-grave-you-cannot-climb-out-of`, lastModified: new Date('2026-04-05'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/feeling-empty-and-exhausted-how-to-find-strength-when-you-have-nothing`, lastModified: new Date('2026-04-26'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/if-your-church-does-not-change-you-change-your-church`, lastModified: new Date('2023-07-02'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/dont-pray-the-storm-away-why-you-need-the-storm`, lastModified: new Date('2024-01-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/birth-of-the-great-christmas-sermon-matthew-1-21`, lastModified: new Date('2022-12-25'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/born-original-marked-by-god-identity-purpose`, lastModified: new Date('2025-08-30'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/god-will-finish-what-he-started-in-you-battle`, lastModified: new Date('2025-11-09'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/experiencing-gods-presence-direct-divine-communication`, lastModified: new Date('2025-09-14'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-your-biggest-battle-follows-your-best-decision`, lastModified: new Date('2026-05-10'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-dont-know-who-you-are-yet`, lastModified: new Date('2026-05-03'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-principle-that-activates-everything`, lastModified: new Date('2026-04-26'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-some-problems-wont-leave-until-you-understand-this`, lastModified: new Date('2026-04-19'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-love-god-but-are-you-in-the-game`, lastModified: new Date('2026-04-05'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/dying-right-good-friday-message`, lastModified: new Date('2026-04-03'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-knowing-is-the-problem`, lastModified: new Date('2026-02-15'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/when-good-things-block-god-things`, lastModified: new Date('2026-02-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/your-resolution-didnt-fail-you-quit-acting`, lastModified: new Date('2026-01-25'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-system-youre-praying-against-without-knowing-it`, lastModified: new Date('2026-01-18'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-does-your-life-keep-collapsing`, lastModified: new Date('2026-01-11'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-some-things-refuse-to-move`, lastModified: new Date('2026-01-04'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-your-prayers-are-not-changing-your-life`, lastModified: new Date('2026-01-04'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-principles-that-move-people-forward-faster`, lastModified: new Date('2026-03-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/why-youre-not-moving-forward-and-how-to-break-it`, lastModified: new Date('2026-03-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/what-if-someone-else-finishes-what-was-meant-for-you`, lastModified: new Date('2026-02-22'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/follow-your-inner-voice-discover-your-destiny`, lastModified: new Date('2026-02-24'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/be-a-doer-of-gods-word-not-just-a-hearer`, lastModified: new Date('2026-02-16'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/pruning-for-progress`, lastModified: new Date('2025-11-02'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-spiritual-weapon-declaration`, lastModified: new Date('2025-10-26'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-spiritual-weapon-no-one-speaks-about`, lastModified: new Date('2025-10-19'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/no-more-waiting-rooms-god-is-live-now`, lastModified: new Date('2025-09-28'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-silent-assassin-of-destiny`, lastModified: new Date('2025-08-31'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-anointing-that-makes-hell-fear-you`, lastModified: new Date('2025-08-24'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/releasing-his-presence`, lastModified: new Date('2025-06-29'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/faith-is-the-router-that-connects-you-to-gods-supply`, lastModified: new Date('2025-06-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/hosting-the-presence-of-god`, lastModified: new Date('2025-06-22'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-danger-of-overnight-success`, lastModified: new Date('2025-05-18'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/speak-prophetic-into-your-life`, lastModified: new Date('2025-04-06'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-prophetic-encounter`, lastModified: new Date('2025-02-23'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-language-of-the-spirit-interpreting-what-you-hear`, lastModified: new Date('2025-02-09'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/the-inheritance-test`, lastModified: new Date('2024-09-08'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/sermons/you-are-not-lazy-you-are-a-lot-more`, lastModified: new Date('2024-01-28'), changeFrequency: 'monthly', priority: 0.6 },
    // Resources (Tier 1 - broad audience, problem-first SEO content)
    { url: `${base}/resources`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/resources/why-does-my-life-feel-empty`, lastModified: new Date('2026-04-27'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/resources/how-to-forgive-someone-who-is-not-sorry`, lastModified: new Date('2026-04-28'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/resources/what-to-do-when-you-feel-stuck`, lastModified: new Date('2026-04-28'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/resources/why-do-good-people-suffer`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/resources/how-to-start-over`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.7 },
    // Devotional (Tier 2 - existing community, Saturday prep)
    { url: `${base}/devotional`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${base}/devotional/prepare-your-heart-before-you-walk-in`, lastModified: new Date('2026-04-27'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/devotional/when-god-seems-silent`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/devotional/one-question-before-sunday`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/devotional/what-sunday-is-not`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/devotional/the-week-did-not-go-as-planned`, lastModified: new Date('2026-05-01'), changeFrequency: 'monthly', priority: 0.6 },
    // Stories (Tier 3 - donor-targeted impact content)
    { url: `${base}/stories`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/stories/what-your-giving-does-in-pretoria-north`, lastModified: new Date('2026-04-27'), changeFrequency: 'monthly', priority: 0.7 },
    // Legal
    { url: `${base}/privacy-policy`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/cookie-policy`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/terms`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
  ]
}
