// AUTO-GENERATED by scripts/prayer-web/prayer_pages.py - do not edit by hand.
export type WeeklyPrayer = { slug: string; date: string; dateDisplay: string; week: number; year: number; weekLabel: string; title: string; theme: string; scriptureRef: string }
export const prayers: WeeklyPrayer[] = [
  {
    "slug": "a-prayer-when-you-are-too-tired-to-keep-going",
    "date": "2026-09-07",
    "dateDisplay": "7 September 2026",
    "week": 37,
    "year": 2026,
    "weekLabel": "Week 37 of 2026",
    "title": "A Prayer When You Are Too Tired to Keep Going",
    "theme": "Resting in God's Sovereignty",
    "scriptureRef": "Isaiah 40:28-31"
  },
  {
    "slug": "a-prayer-for-the-courage-to-follow-through",
    "date": "2026-08-31",
    "dateDisplay": "31 August 2026",
    "week": 36,
    "year": 2026,
    "weekLabel": "Week 36 of 2026",
    "title": "A Prayer for the Courage to Follow Through",
    "theme": "The Power of Obedience",
    "scriptureRef": "Deuteronomy 28:1-2"
  },
  {
    "slug": "a-prayer-when-you-want-to-change-but-keep-slipping",
    "date": "2026-08-24",
    "dateDisplay": "24 August 2026",
    "week": 35,
    "year": 2026,
    "weekLabel": "Week 35 of 2026",
    "title": "A Prayer When You Want to Change but Keep Slipping",
    "theme": "Pursuing Holiness in Daily Life",
    "scriptureRef": "1 Peter 1:15-16"
  },
  {
    "slug": "a-prayer-for-when-you-dont-know-what-comes-next",
    "date": "2026-08-17",
    "dateDisplay": "17 August 2026",
    "week": 34,
    "year": 2026,
    "weekLabel": "Week 34 of 2026",
    "title": "A Prayer for When You Don't Know What Comes Next",
    "theme": "Trusting God in Uncertainty",
    "scriptureRef": "Proverbs 3:5-6"
  },
  {
    "slug": "a-prayer-when-you-cannot-hear-gods-voice",
    "date": "2026-08-10",
    "dateDisplay": "10 August 2026",
    "week": 33,
    "year": 2026,
    "weekLabel": "Week 33 of 2026",
    "title": "A Prayer When You Cannot Hear God's Voice",
    "theme": "Hearing God's Voice",
    "scriptureRef": "John 10:27"
  },
  {
    "slug": "a-prayer-for-when-life-keeps-knocking-you-down",
    "date": "2026-08-03",
    "dateDisplay": "3 August 2026",
    "week": 32,
    "year": 2026,
    "weekLabel": "Week 32 of 2026",
    "title": "A Prayer for When Life Keeps Knocking You Down",
    "theme": "Persevering Through Trials",
    "scriptureRef": "James 1:2-4"
  },
  {
    "slug": "a-prayer-when-you-never-feel-like-you-have-enough",
    "date": "2026-07-27",
    "dateDisplay": "27 July 2026",
    "week": 31,
    "year": 2026,
    "weekLabel": "Week 31 of 2026",
    "title": "A Prayer When You Never Feel Like You Have Enough",
    "theme": "Finding Contentment in Christ",
    "scriptureRef": "Philippians 4:11-13"
  },
  {
    "slug": "a-prayer-when-you-cannot-forgive-someone-who-hurt-you",
    "date": "2026-07-20",
    "dateDisplay": "20 July 2026",
    "week": 30,
    "year": 2026,
    "weekLabel": "Week 30 of 2026",
    "title": "A Prayer When You Cannot Forgive Someone Who Hurt You",
    "theme": "Embracing Forgiveness",
    "scriptureRef": "Ephesians 4:31-32"
  },
  {
    "slug": "a-prayer-for-when-you-feel-like-giving-up-on-faith",
    "date": "2026-07-13",
    "dateDisplay": "13 July 2026",
    "week": 29,
    "year": 2026,
    "weekLabel": "Week 29 of 2026",
    "title": "A Prayer for When You Feel Like Giving Up on Faith",
    "theme": "Standing Firm In Faith",
    "scriptureRef": "Hebrews 10:35-36"
  },
  {
    "slug": "a-prayer-for-when-you-cant-feel-thankful-anymore",
    "date": "2026-07-06",
    "dateDisplay": "6 July 2026",
    "week": 28,
    "year": 2026,
    "weekLabel": "Week 28 of 2026",
    "title": "A Prayer for When You Can't Feel Thankful Anymore",
    "theme": "Living a Life of Gratitude",
    "scriptureRef": "1 Thessalonians 5:16-18"
  },
  {
    "slug": "a-prayer-when-you-keep-doing-the-thing-you-hate",
    "date": "2026-06-29",
    "dateDisplay": "29 June 2026",
    "week": 27,
    "year": 2026,
    "weekLabel": "Week 27 of 2026",
    "title": "A Prayer When You Keep Doing the Thing You Hate",
    "theme": "Walking in Genuine Repentance",
    "scriptureRef": "2 Corinthians 7:10"
  },
  {
    "slug": "a-prayer-when-you-dont-know-what-to-do-next",
    "date": "2026-06-22",
    "dateDisplay": "22 June 2026",
    "week": 26,
    "year": 2026,
    "weekLabel": "Week 26 of 2026",
    "title": "A Prayer When You Don't Know What to Do Next",
    "theme": "Surrendering to God's Plan",
    "scriptureRef": "Proverbs 3:5-6"
  },
  {
    "slug": "a-prayer-for-when-you-are-tired-of-waiting",
    "date": "2026-06-15",
    "dateDisplay": "15 June 2026",
    "week": 25,
    "year": 2026,
    "weekLabel": "Week 25 of 2026",
    "title": "A Prayer for When You Are Tired of Waiting",
    "theme": "Waiting on God Without Losing Heart",
    "scriptureRef": "Isaiah 40:31"
  }
]
