// AUTO-GENERATED by scripts/prayer-web/prayer_pages.py - do not edit by hand.
export type WeeklyPrayer = { slug: string; date: string; dateDisplay: string; week: number; year: number; weekLabel: string; title: string; theme: string; scriptureRef: string }
export const prayers: WeeklyPrayer[] = [
  {
    "slug": "a-prayer-when-you-are-too-tired-to-keep-going",
    "date": "2026-09-07",
    "dateDisplay": "7 September 2026",
    "week": 37,
    "year": 2026,
    "weekLabel": "Week 37 of 2026",
    "title": "A Prayer When You Are Too Tired to Keep Going",
    "theme": "Resting in God's Sovereignty",
    "scriptureRef": "Isaiah 40:28-31"
  }
]
